export component AlbumItem inherits VerticalLayout {
    padding-bottom: 15px;
    Rectangle {
        Image {
            width: 100%;
            height: 100%;
            source: @image-url("../../../placeholder/500x500.png");
        }

        border-radius: 4px;
        clip: true;
    }

    VerticalLayout {
        padding-top: 8px;

        Text {
            text: "Album Title";
            color: white;
            font-size: 17px;
            font-weight: 500;
            vertical-stretch: 0;
        }
    }

    VerticalLayout {
        padding-top: 4px;
        Text {
            text: "Album Artist";
            color: white;
            font-size: 15px;
            vertical-stretch: 0;
            opacity: 0.8;
        }
    }
}
