import { ScrollView } from "std-widgets.slint";
import { AlbumItem, AlbumItemData } from "./album-item.slint";

export component AlbumList inherits ScrollView {
    in property <length> item-width;
    in property <length> item-height;
    in property <[AlbumItemData]> items: [];
    width: 100%;
    height: item-height;
    viewport-height: item-height - 15px;
    vertical-scrollbar-policy: always-off;
    horizontal-scrollbar-policy: always-off;
    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 24px;
        for album in root.items: AlbumItem {
            width: root.item-width;
            height: root.item-height;
            data: album;
        }
    }
}
