export component AlbumItem inherits VerticalLayout {
    in property <image> cover-image;
    in property <string> title;
    in property <string> artist;
    padding-bottom: 15px;
    Rectangle {
        width: root.width;
        height: root.width;
        Image {
            width: 100%;
            height: 100%;
            source: root.cover-image.width > 0 ? root.cover-image : @image-url("../../../placeholder/500x500.png");
            image-fit: cover;
        }

        border-radius: 4px;
        clip: true;
    }

    VerticalLayout {
        padding-top: 8px;

        Text {
            text: root.title;
            color: white;
            font-size: 17px;
            font-weight: 500;
            vertical-stretch: 0;
            overflow: elide;
        }
    }

    VerticalLayout {
        padding-top: 4px;
        Text {
            text: root.artist;
            color: white;
            font-size: 15px;
            vertical-stretch: 0;
            opacity: 0.8;
            overflow: elide;
        }
    }
}
