import { ScrollView } from "std-widgets.slint";
import { AlbumItem } from "./album-item.slint";

export component AlbumList inherits ScrollView {
    in property <length> item-width;
    in property <length> item-height;
    width: 100%;
    height: item-height;
    viewport-height: item-height - 15px;
    vertical-scrollbar-policy: always-off;
    horizontal-scrollbar-policy: always-off;
    HorizontalLayout {
        padding-left: 12px;
        padding-right: 12px;
        spacing: 24px;
        for i in 20: AlbumItem {
            width: root.item-width;
            height: root.item-height;
        }
    }
}
