export struct AlbumItemData {
    cover-image: image,
    title: string,
    artist: string,
}

export component AlbumItem inherits VerticalLayout {
    in property <AlbumItemData> data: {
        cover-image: @image-url(""),
        title: "Unknown Album",
        artist: "Unknown Artist",
    };
    padding-bottom: 15px;
    Rectangle {
        width: root.width;
        height: root.width;
        Image {
            width: 100%;
            height: 100%;
            source: root.data.cover-image;
            image-fit: cover;
        }

        border-radius: 4px;
        clip: true;
    }

    VerticalLayout {
        padding-top: 8px;

        Text {
            text: root.data.title;
            color: white;
            font-size: 17px;
            font-weight: 500;
            vertical-stretch: 0;
            overflow: elide;
        }
    }

    VerticalLayout {
        padding-top: 4px;
        Text {
            text: root.data.artist;
            color: white;
            font-size: 15px;
            vertical-stretch: 0;
            opacity: 0.8;
            overflow: elide;
        }
    }
}
