import { IconType } from "$lib/icon/types";
import {
	Undo2,
	BrushCleaning,
	GripVertical,
	FileText,
	Expand,
	Settings,
	Lock,
	Search,
	Music2,
	PauseCircle,
	PlayCircle,
	HelpCircle,
	ListPlus,
	Repeat,
	Repeat1,
	Shuffle,
	SkipBack,
	SkipForward,
	Volume2,
	VolumeX,
	Trash2,
	XCircle,
	KeyboardMusic,
	CircleX, ChartNoAxesColumn,
} from "@lucide/svelte";

const iconRegistryLucide = {
	[IconType.Unknown]: HelpCircle,
	[IconType.Play]: PlayCircle,
	[IconType.Pause]: PauseCircle,
	[IconType.Previous]: SkipBack,
	[IconType.Next]: SkipForward,
	[IconType.Playing]: Music2,
	[IconType.Note]: Music2,
	[IconType.PlayBack]: Undo2,
	[IconType.Back]: Undo2,
	[IconType.AlbumBack]: Undo2,
	[IconType.Speaker]: Volume2,
	[IconType.Mute]: VolumeX,
	[IconType.Remove]: XCircle,
	[IconType.Trash]: Trash2,
	[IconType.Settings]: Settings,
	[IconType.Search]: Search,
	[IconType.QueuePlaylist]: ListPlus,
	[IconType.CleanPlaylist]: BrushCleaning,
	[IconType.RepeatNone]: Repeat,
	[IconType.RepeatPlayNone]: Repeat,
	[IconType.Repeat]: Repeat,
	[IconType.RepeatOne]: Repeat1,
	[IconType.Shuffle]: Shuffle,
	[IconType.Fullscreen]: Expand,
	[IconType.DragOn]: GripVertical,
	[IconType.DragOff]: Lock,
	[IconType.SaveLog]: FileText,
	[IconType.Equalizer]: KeyboardMusic,
	[IconType.Close]: CircleX,
	[IconType.Visualizer]: ChartNoAxesColumn,
};

export default iconRegistryLucide;
