import { IconType } from "$lib/ui/icon/types";
import {
    ArrowUUpLeft,
    Broom,
    DotsSixVertical,
    FileText,
    FrameCorners,
    Gear,
    LockSimple,
    MagnifyingGlass,
    MusicNote,
    MusicNotes,
    PauseCircle,
    PlayCircle,
    QuestionMark,
    Queue,
    Repeat,
    RepeatOnce,
    Shuffle,
    SkipBackCircle,
    SkipForwardCircle,
    SpeakerHigh,
    SpeakerX,
    Trash,
    XCircle,
    Faders,
    ChartBar,
    Folder,
    CaretUp,
    CaretDown, GridFour, VinylRecord,
} from "phosphor-svelte";

const iconRegistryPhospor = {
	[IconType.Unknown]: QuestionMark,
	[IconType.Play]: PlayCircle,
	[IconType.Pause]: PauseCircle,
	[IconType.Previous]: SkipBackCircle,
	[IconType.Next]: SkipForwardCircle,
	[IconType.Playing]: MusicNotes,
	[IconType.Note]: MusicNote,
	[IconType.PlayBack]: ArrowUUpLeft,
	[IconType.Back]: ArrowUUpLeft,
	[IconType.AlbumBack]: ArrowUUpLeft,
	[IconType.Speaker]: SpeakerHigh,
	[IconType.Mute]: SpeakerX,
	[IconType.Remove]: XCircle,
	[IconType.Trash]: Trash,
	[IconType.Settings]: Gear,
	[IconType.Search]: MagnifyingGlass,
	[IconType.QueuePlaylist]: Queue,
	[IconType.CleanPlaylist]: Broom,
	[IconType.RepeatNone]: Repeat,
	[IconType.RepeatPlayNone]: Repeat,
	[IconType.Repeat]: Repeat,
	[IconType.RepeatOne]: RepeatOnce,
	[IconType.Shuffle]: Shuffle,
	[IconType.Fullscreen]: FrameCorners,
	[IconType.DragOn]: DotsSixVertical,
	[IconType.DragOff]: LockSimple,
	[IconType.SaveLog]: FileText,
	[IconType.Equalizer]: Faders,
	[IconType.Close]: XCircle,
	[IconType.Visualizer]: ChartBar,
	[IconType.Folder]: Folder,
	[IconType.SortAsc]: CaretUp,
	[IconType.SortDesc]: CaretDown,
    [IconType.MusicListTypeAll]: GridFour,
    [IconType.MusicListTypeAlbum]: VinylRecord,
    [IconType.MusicListTypeMusic]: MusicNote,
    [IconType.MusicListTypeFolder]: Folder,
};

export default iconRegistryPhospor;
