import { AlbumList } from "features/album/album-list.slint";
import { MusicList } from "features/music/music-list.slint";
import { Background } from "features/background/background.slint";

import "../fonts/Inter-Regular.ttf";
import "../fonts/Inter-Medium.ttf";
export component AppWindow inherits Window {
    in property <image> background-image;

    in property <length> album-width;
    in property <length> album-height;
    
    in property <length> music-width;
    in property <length> music-list-height;
    in property <int> music-list-column: 1;

    background: transparent;
    default-font-family: "Inter";

    Background {
        image: root.background-image;
    }

    VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: start;

        AlbumList {
            item-width: root.album-width;
            item-height: root.album-height;
        }

        MusicList {
            item-width: root.music-width;
            height: root.music-list-height;
            column: root.music-list-column;
        }
    }
}
