import { AlbumList } from "features/album/album-list.slint";
import { MusicList } from "features/music/music-list.slint";
import { Background } from "features/background/background.slint";

import "../fonts/Inter-Regular.ttf";
import "../fonts/Inter-Medium.ttf";
export component AppWindow inherits Window {
    in property <image> background-image;
    background: transparent;
    default-font-family: "Inter";

    Background {
        image: root.background-image;
    }

    VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: start;

        AlbumList { }

        MusicList { }
    }
}
