import { AlbumList } from "features/album/album-list.slint";
import { MusicList, MusicItemData } from "features/music/music-list.slint";
import { Background } from "features/background/background.slint";

import "../fonts/Inter-Regular.ttf";
import "../fonts/Inter-Medium.ttf";
export component AppWindow inherits Window {
    in property <image> background-image;

    in property <length> album-width: 200px;
    in property <length> album-height: 250px;

    in property <percent> music-width: 100%;
    in property <length> music-list-height: 500px;
    in property <int> music-list-column: 1;
    in property <[MusicItemData]> music-items: [];

    in property <bool> is-visible: false;
    
    // Progressive loading callback
    callback request-images(int, int);

    background: transparent;
    default-font-family: "Inter";

    if root.is-visible: Background {
        image: root.background-image;
    }

    if root.is-visible: VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: start;

        AlbumList {
            item-width: root.album-width;
            item-height: root.album-height;
        }

        MusicList {
            item-width: root.music-width;
            height: root.music-list-height;
            column: root.music-list-column;
            items: root.music-items;
            request-images(start, end) => {
                root.request-images(start, end);
            }
        }
    }
}
